<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book [
<!ELEMENT book (title,CLC,date,publisher,price,author,introduction)>
<!ELEMENT data (year,month)>
<!ELEMENT author (first,second)>
<!ELEMENT bookstore (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT CLC (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT book (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT introduction (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT second (#PCDATA)>
]>

<bookstore>
<book name="易经">
	<title>易经</title>
	<CLC>B221/11</CLC>
	<date>
		<year>1989</year>
		<month>7</month>
	</date>
	<publisher>北京大学出版社</publisher>
	<price>1.85元</price>
</book>

<book name="周易尚氏学">
	<title>周易尚氏学</title>
	<author>尚秉和</author>
	<CLC>B221/1</CLC>
	<date>
		<year>1980</year>
		<month>5</month>
	</date>
	<publisher>中华书局</publisher>
	<price>1.4元</price>
</book>

<book name="玄奘哲学研究">
	<title>玄奘哲学研究</title>
	<author>天光烈</author>
	<CLC>B949.2/25</CLC>
	<date>
		<year>1986</year>
		<month>10</month>
	</date>
	<publisher>学林出版社</publisher>
	<price>1.65元</price>
	<introduction>本书对玄奘的生平、时代背景及其哲学思想的渊源于辩证法的因素等加以论述
	</introduction>
</book>

<book name="缩影图书资料管理">
	<title>缩影图书资料管理</title>
	<author>王会均</author>
	<CLC>G255.72/2</CLC>
	<date>
		<year>1933</year>
	</date>
	<publisher>文史哲出版社</publisher>
	<price>37.6元</price>
</book>

<book name="红楼梦：三家评本">
	<title>红楼梦：三家评本</title>
	<author>
		<first>曹雪芹</first>
		<second>高鹗</second>
	</author>
	<CLC>813.351/5510.46</CLC>
	<date>
		<year>1988</year>
		<month>10</month>
	</date>
	<publisher>上海古籍出版社</publisher>
	<price>14.4元</price>
</book>

<book name="明代理学研究">
	<title>明代理学研究</title>
	<author>古清美</author>
	<CLC>B248.05/2</CLC>
	<date>
		<year>1990</year>
	</date>
	<publisher>大安出版社</publisher>
	<price>63.25元</price>
</book>

</bookstore>